import './globals.scss';
import Navbar from '@/components/Navbar';
import Stats from '@/components/Stats';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* <Stats /> */}
        {children}
      </body>
    </html>
  );
}
